const types = {
  GET_SETTINGS: 'GET_SETTINGS',
  GET_RANDOM_NUMBERS: 'GET_RANDOM_NUMBERS',
  CREATE_MATRIX: 'CREATE_MATRIX',
  INCREMENT_CELL: 'INCREMENT_CELL',
  ADD_ROW: 'ADD_ROW',
  DELETE_ROW: 'DELETE_ROW',
  // ROW_SUM: 'ROW_SUM',
};
export default types;
