const types = {
  SET_SETTINGS: 'GET_SETTINGS',
  GET_RANDOM_NUMBERS: 'GET_RANDOM_NUMBERS',
  CREATE_MATRIX: 'CREATE_MATRIX',
  INCREMENT_CELL: 'INCREMENT_CELL',
  ADD_ROW: 'ADD_ROW',
  DELETE_ROW: 'DELETE_ROW',
  SET_NEAREST_CELLS: 'SET_NEAREST_CELLS',
  RESET_NEAREST_CELLS: 'RESET_NEAREST_CELLS', 
};
export default types;
