const types = {
  SET_SETTINGS: 'SET_SETTINGS',
  CREATE_MATRIX: 'CREATE_MATRIX',
  INCREMENT_CELL: 'INCREMENT_CELL',
  ADD_ROW: 'ADD_ROW',
  DELETE_ROW: 'DELETE_ROW',
  SET_NEAREST_CELLS: 'SET_NEAREST_CELLS',
  RESET_NEAREST_CELLS: 'RESET_NEAREST_CELLS',
};
export default types;
